using System;
using System.Globalization;
using System.IO;
using Argus.Simulation.Core;
using UnityEngine;

namespace Argus.Simulation.Unity
{
    public sealed class AnalyticOrbitStateSource : MonoBehaviour, ISpacecraftStateSource
    {
        [SerializeField] private string epochUtc = "2025-01-15T00:00:00Z";
        [SerializeField, Min(100_000f)] private double altitudeMeters = 500_000.0;
        [SerializeField, Range(0f, 180f)] private double inclinationDegrees = 51.6;
        [SerializeField, Range(0f, 360f)] private double raanDegrees;
        [SerializeField, Range(0f, 360f)] private double phaseDegrees;

        [Tooltip("Use SPICE Earth orientation. Off falls back to a constant spin with zero angle at the epoch.")]
        [SerializeField] private bool useSpiceEphemeris = true;

        [Tooltip("Reference file under StreamingAssets, generated by Argus.Spice/regenerate.sh.")]
        [SerializeField] private string spiceEphemerisFile = "Argus/Spice/foundation_one_orbit.json";

        private AnalyticSimulationEngine _engine;
        private IEphemerisProvider _ephemeris;
        private bool _ephemerisLoadFailed;
        private Vector3 _manualAttitudeOffsetDegrees;

        public IEphemerisProvider Ephemeris => _ephemeris;

        public bool UseSpiceEphemeris
        {
            get => useSpiceEphemeris;
            set
            {
                useSpiceEphemeris = value;
                OnValidate();
            }
        }

        // Path relative to StreamingAssets.
        public string SpiceEphemerisFile
        {
            get => spiceEphemerisFile;
            set
            {
                spiceEphemerisFile = value;
                OnValidate();
            }
        }

        // Body-frame offset applied on top of nadir tracking to every produced state, so the
        // rendered pose and the sensors share one attitude. Unity Euler order, as the pose UI uses.
        public Vector3 ManualAttitudeOffsetDegrees => _manualAttitudeOffsetDegrees;

        public double AltitudeMeters
        {
            get => altitudeMeters;
            set
            {
                altitudeMeters = Math.Max(100_000.0, Math.Min(2_000_000.0, value));
                _engine = null;
            }
        }

        public double PhaseDegrees
        {
            get => phaseDegrees;
            set
            {
                phaseDegrees = ((value % 360.0) + 360.0) % 360.0;
                _engine = null;
            }
        }
        public double EstimatedPeriodSeconds
        {
            get
            {
                double radius = CircularOrbitModel.EarthEquatorialRadiusMeters + altitudeMeters;
                return 2.0 * Math.PI * Math.Sqrt(
                    radius * radius * radius / CircularOrbitModel.EarthGravitationalParameter);
            }
        }

        public bool TryGetState(long sequence, double simulationTimeSeconds, out SpacecraftState state)
        {
            if (_engine == null && !TryBuildEngine())
            {
                state = default;
                return false;
            }

            ActuatorCommandSet commands = ActuatorCommandSet.None(sequence, simulationTimeSeconds);
            SimulationStepInput input = new SimulationStepInput(
                sequence,
                simulationTimeSeconds,
                commands);
            if (!_engine.TryStep(input, out SimulationSnapshot snapshot))
            {
                state = default;
                return false;
            }

            state = snapshot.Spacecraft;
            if (_manualAttitudeOffsetDegrees != Vector3.zero)
            {
                Quaternion offset = Quaternion.Euler(_manualAttitudeOffsetDegrees);
                // Unity's offset is single precision; renormalize so the attitude stays unit at double precision.
                state = state.WithBodyToEcef(
                    (state.BodyToEcef * new Quaterniond(offset.x, offset.y, offset.z, offset.w)).Normalized());
            }

            return state.IsValid;
        }

        public bool TryGetSunObservation(SpacecraftState state, out SunObservation observation)
        {
            if (_ephemeris == null ||
                !_ephemeris.TryGetSample(state.SimulationTimeSeconds, out EphemerisSample environment))
            {
                observation = default;
                return false;
            }

            observation = SolarGeometry.Observe(state, environment);
            return true;
        }

        public void NudgeAttitude(Vector3 deltaDegrees)
        {
            Vector3 offset = _manualAttitudeOffsetDegrees + deltaDegrees;
            _manualAttitudeOffsetDegrees = new Vector3(
                NormalizeAngle(offset.x),
                NormalizeAngle(offset.y),
                NormalizeAngle(offset.z));
        }

        public void ResetManualAttitude()
        {
            _manualAttitudeOffsetDegrees = Vector3.zero;
        }

        private bool TryBuildEngine()
        {
            if (!DateTimeOffset.TryParse(
                    epochUtc,
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                    out DateTimeOffset parsedEpoch))
            {
                Debug.LogError($"Invalid UTC epoch: {epochUtc}", this);
                return false;
            }

            if (useSpiceEphemeris && _ephemeris == null && !TryLoadEphemeris())
            {
                return false;
            }

            AnalyticSimulationEngine engine = new AnalyticSimulationEngine(
                altitudeMeters,
                inclinationDegrees,
                raanDegrees,
                phaseDegrees,
                useSpiceEphemeris ? _ephemeris : null);
            try
            {
                engine.Initialize(new SimulationConfiguration(
                    "unity-preview",
                    parsedEpoch,
                    0.1));
            }
            catch (ArgumentException error)
            {
                Debug.LogError(error.Message, this);
                return false;
            }

            _engine = engine;
            return true;
        }

        private bool TryLoadEphemeris()
        {
            if (_ephemerisLoadFailed)
            {
                return false;
            }

            string path = Path.Combine(Application.streamingAssetsPath, spiceEphemerisFile);
            try
            {
                _ephemeris = SpiceReferenceFile.Load(File.ReadAllText(path));
                return true;
            }
            catch (Exception error) when (error is IOException || error is FormatException ||
                                          error is UnauthorizedAccessException || error is ArgumentException)
            {
                _ephemerisLoadFailed = true;
                Debug.LogError($"Could not load SPICE ephemeris '{path}': {error.Message}", this);
                return false;
            }
        }

        private static float NormalizeAngle(float angle) => Mathf.Repeat(angle + 180f, 360f) - 180f;

        private void OnValidate()
        {
            _engine = null;
            _ephemeris = null;
            _ephemerisLoadFailed = false;
        }
    }
}
